[package]
name = "lurk-hs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hs-bindgen = { version = "0.8.0", features = ["full"] }
lurk = "0.3.1"

[lib]
crate-type = ["staticlib"]
